### ISSUE TITLE
Add terraform-aws-lambda-datadog to OpenTofu registry

### ISSUE THREAD

**Issue by payton** [DataDog/terraform-aws-lambda-datadog#16]
Hey there! We'd love if this module could be added to the OpenTofu registry https://opentofu.org/registry/. It's currently not supported by OpenTofu users without it.

Instructions on adding it are in their README https://github.com/opentofu/registry/?tab=readme-ov-file#adding-providers-modules-or-gpg-keys-to-the-opentofu-registry

**Comment by duncanpharvey** [comment]
Hi @payton! Thanks for pointing this out. We'll look into this and share here when we have an update.

**Comment by dobeerman** [comment]
Hi all,
Any updates here? ;)

**Comment by duncanpharvey** [comment]
I submitted the module to OpenTofu this morning. Here is the related Github Issue and PR so you can follow along:

- https://github.com/opentofu/registry/issues/933
- https://github.com/opentofu/registry/pull/934

**Comment by Yantrio** [comment]
Hey 👋 I just merged those into the opentofu registry. These should be available for usage soon!

**Comment by duncanpharvey** [comment]
Thank you @Yantrio! How should we go about keeping the module version in the OpenTofu registry up to date with the module version available in the Terraform Registry? Is that automatic or do we need to submit a PR with each new version?

**Comment by Yantrio** [comment]
It's completely automatic :) we will periodically scrape the github repo for new releases.

**Comment by duncanpharvey** [comment]
Excellent! Thanks for your help.
