### ISSUE TITLE
Lambda layers are not supported for functions created with container images.

### ISSUE THREAD

**Issue by mf-gganz** [DataDog/terraform-aws-lambda-datadog#2]
Attempted to use this while passing an `image_uri` and get the warning

```
InvalidParameterValueException: Lambda layers are not supported for functions created with container images.
```

I'm assuming this is expected, but it would probably make sense to remove those as inputs, and make a note in the readme if its not a supported case.

**Comment by duncanpharvey** [comment]
Hey @mf-gganz thanks for reaching out! Indeed Lambda functions created with container images are not supported by this module. We'll make updates to the module and documentation to reflect this and will share here once complete.

**Comment by duncanpharvey** [comment]
Check added and documentation updated in `v1.1.0`!

https://github.com/DataDog/terraform-aws-lambda-datadog/releases/tag/v1.1.0
